[2025-04-29T03:01:03.065+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T03:01:03.092+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-28T02:30:00+00:00 [queued]>
[2025-04-29T03:01:03.101+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-28T02:30:00+00:00 [queued]>
[2025-04-29T03:01:03.102+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-29T03:01:03.115+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-04-28 02:30:00+00:00
[2025-04-29T03:01:03.137+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5490) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T03:01:03.141+0000] {standard_task_runner.py:72} INFO - Started process 5499 to run task
[2025-04-29T03:01:03.147+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_final_etl', 'load_sentiment_data_to_snowflake', 'scheduled__2025-04-28T02:30:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl.py', '--cfg-path', '/tmp/tmp1e3gqag8']
[2025-04-29T03:01:03.156+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask load_sentiment_data_to_snowflake
[2025-04-29T03:01:03.262+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-28T02:30:00+00:00 [running]> on host 5891a65dc7e9
[2025-04-29T03:01:03.395+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_final_etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T02:30:00+00:00'
[2025-04-29T03:01:03.398+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-29T03:01:04.675+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T03:01:05.128+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T03:07:39.889+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T03:07:39.959+0000] {logging_mixin.py:190} INFO - âœ… Sentiment data loaded into dev.raw.tesla_tweet_data (full refresh).
[2025-04-29T03:07:39.976+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-29T03:07:40.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-29T03:07:40.273+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tesla_stock_sentiment_final_etl, task_id=load_sentiment_data_to_snowflake, run_id=scheduled__2025-04-28T02:30:00+00:00, execution_date=20250428T023000, start_date=20250429T030103, end_date=20250429T030740
[2025-04-29T03:07:40.426+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-29T03:07:40.482+0000] {taskinstance.py:3925} ERROR - Error scheduling downstream tasks. Skipping it as this is entirely optional optimisation. There might be various reasons for it, please take a look at the stack trace to figure out if the root cause can be diagnosed and fixed. See the issue https://github.com/apache/***/issues/39717 for details and an example problem. If you would like to get help in solving root cause, open discussion with all details with your managed service support or in Airflow repository.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3921, in schedule_downstream_tasks
    return TaskInstance._schedule_downstream_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3870, in _schedule_downstream_tasks
    partial_dag = task.dag.partial_subset(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 2664, in partial_subset
    t.task_id: _deepcopy_task(t)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 2661, in _deepcopy_task
    return copy.deepcopy(t, memo)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 143, in deepcopy
    y = copier(memo)
        ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1388, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 201, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.lock' object
[2025-04-29T03:07:40.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-29T17:28:41.257+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T17:28:41.283+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-28T02:30:00+00:00 [queued]>
[2025-04-29T17:28:41.295+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-28T02:30:00+00:00 [queued]>
[2025-04-29T17:28:41.296+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-29T17:28:41.313+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_sentiment_data_to_snowflake> on 2025-04-28 02:30:00+00:00
[2025-04-29T17:28:41.329+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T17:28:41.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_stock_sentiment_final_etl', 'load_sentiment_data_to_snowflake', 'scheduled__2025-04-28T02:30:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl.py', '--cfg-path', '/tmp/tmpsnlmg5ia']
[2025-04-29T17:28:41.331+0000] {standard_task_runner.py:72} INFO - Started process 299 to run task
[2025-04-29T17:28:41.332+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask load_sentiment_data_to_snowflake
[2025-04-29T17:28:41.405+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_stock_sentiment_final_etl.load_sentiment_data_to_snowflake scheduled__2025-04-28T02:30:00+00:00 [running]> on host 1f133dc6a737
[2025-04-29T17:28:41.512+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_stock_sentiment_final_etl' AIRFLOW_CTX_TASK_ID='load_sentiment_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T02:30:00+00:00'
[2025-04-29T17:28:41.514+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-29T17:28:41.532+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-29T17:28:41.533+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-29T17:28:41.535+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-29T17:28:41.535+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-29T17:28:43.002+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T17:28:43.182+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T17:51:08.182+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-29T17:51:08.228+0000] {logging_mixin.py:190} INFO - âœ… Sentiment data loaded into dev.raw.tesla_tweet_data.
[2025-04-29T17:51:08.242+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-29T17:51:08.385+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-29T17:51:08.389+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tesla_stock_sentiment_final_etl, task_id=load_sentiment_data_to_snowflake, run_id=scheduled__2025-04-28T02:30:00+00:00, execution_date=20250428T023000, start_date=20250429T172841, end_date=20250429T175108
[2025-04-29T17:51:08.500+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-29T17:51:08.624+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T17:51:08.628+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
